version: '3.8'

services:
  motorcycle:
    image: motorcycle
    container_name: motorcycle-container
    ports:
      - 8680:8680
    volumes:
      - motorcycle_data:/var/lib/motorcycle/data
    depends_on:
      - rabbitmq
      - postgresql
      - mongodb
    
  mongodb:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lucas
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  rabbitmq_data:
  postgresql_data:
  motorcycle_data:
